embed_assets: on

javascripts:
  bulk_pets_package:
    - public/javascripts/pet_query.js
    - public/javascripts/pets/bulk.js
    
  edit_outfit_package:
    - public/javascripts/wardrobe.js
    - public/javascripts/outfits/edit.js
  
  new_outfit_package:
    - public/javascripts/pet_query.js
    - public/javascripts/outfits/new.js
