package_assets: off
embed_assets: on

javascripts:
  bulk_pets_package:
    - public/javascripts/ajax_auth.js
    - public/javascripts/pet_query.js
    - public/javascripts/pets/bulk.js
    
  edit_outfit_package:
    - public/javascripts/ajax_auth.js
    - public/javascripts/jquery.jgrowl.js
    - public/javascripts/wardrobe.js
    - public/javascripts/outfits/edit.js
  
  new_outfit_package:
    - public/javascripts/pet_query.js
    - public/javascripts/outfits/new.js
  
  show_outfit_package:
    - public/javascripts/wardrobe.js
    - public/javascripts/outfits/show.js
