development:
  adapter: mysql2
  database: openneo_impress
  username: openneo_impress
  password: openneo_impress
  pool: 5
  variables:
    sql_mode: TRADITIONAL

production:
  url: <%= ENV['DATABASE_URL_PRIMARY'] %>
  variables:
    sql_mode: TRADITIONAL
