development:
  primary:
    # You can override these default settings with this environment variable,
    # fully or partially. We do this in the .devcontainer setup!
    url: <%= ENV['DATABASE_URL_PRIMARY_DEV'] %>
    adapter: mysql2
    database: openneo_impress
    username: impress_dev
    password: impress_dev
    pool: 5
    variables:
      sql_mode: TRADITIONAL

  openneo_id:
    # You can override these default settings with this environment variable,
    # fully or partially. We do this in the .devcontainer setup!
    url: <%= ENV['DATABASE_URL_OPENNEO_ID_DEV'] %>
    adapter: mysql2
    database: openneo_id
    username: impress_dev
    password: impress_dev
    pool: 2
    variables:
      sql_mode: TRADITIONAL
    migrations_paths: db/openneo_id_migrate

production:
  primary:
    url: <%= ENV['DATABASE_URL_PRIMARY'] %>
    variables:
      sql_mode: TRADITIONAL

  openneo_id:
    url: <%= ENV['DATABASE_URL_OPENNEO_ID'] %>
    variables:
      sql_mode: TRADITIONAL
    migrations_paths: db/openneo_id_migrate
