html5:         http://html5shim.googlecode.com/svn/trunk/html5.js
jquery:        http://ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.min.js
jquery_tmpl:   http://ajax.microsoft.com/ajax/jquery.templates/beta1/jquery.tmpl.min.js
swfobject:     http://ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js
