acara: 
  blue: mnbztxxn
  green: obxdjm88
  red: 7njwqlq8
  yellow: o3wj6s77
aisha: 
  blue: n9ozx4z5
  green: vw3j5rnt
  red: r27dkxdc
  yellow: t4osnjxq
blumaroo: 
  blue: 8dng4bvh
  green: xmqmg3m9
  red: j77lzlmx
  yellow: kfonqhdc
bori: 
  blue: cdtgf7jo
  green: 6c8dvw76
  red: tg7hx55j
  yellow: sc2hhvhn
bruce: 
  blue: w3hljbx7
  green: gwgc67tt
  red: 72d26x2b
  yellow: wqz8xn4t
buzz: 
  blue: rkvgtzv3
  green: schfx5c4
  red: gddkkb5j
  yellow: jc9klfxm
chia: 
  blue: d65mc9gf
  green: 8d4949sr
  red: 4lrb4n3f
  yellow: oqs3kzmf
chomby: 
  blue: h3qctoxg
  green: 552mzx7r
  red: 9swsd8ln
  yellow: bdml26md
cybunny: 
  blue: v8shwcoq
  green: xl6msllv
  red: lfkscvgd
  yellow: cwlv6zz9
draik: 
  blue: 2g4jtrfh
  green: 438o4dv5
  red: vd2joxxq
  yellow: bob39shq
elephante: 
  blue: 4ckkjxjj
  green: r22hl9oh
  red: jhhhbrww
  yellow: jf9ww4om
eyrie: 
  blue: m5mvxv23
  green: s42o6oon
  red: 6kngmhvs
  yellow: d6b8fqnm
flotsam: 
  blue: hwdo7rlb
  green: 47vt32x2
  red: xhob45wn
  yellow: r8r7jmvr
gelert: 
  blue: 4g7n9mh5
  green: jfmwlmk8
  red: l95vq4w2
  yellow: 5nrd2lvd
gnorbu: 
  blue: 6c275jcg
  green: ghfgo5tn
  red: qozzjgmg
  yellow: 5lrvftfb
grarrl: 
  blue: j7q65fv4
  green: t3mstkl6
  red: r946sq53
  yellow: jtg67z98
grundo: 
  blue: nwx8v2rb
  green: 5xn4kjf8
  red: qjcb6t8x
  yellow: n2g9d94f
hissi: 
  blue: 7ls55f33
  green: dz5dwsbx
  red: jsfvcqwt
  yellow: z24m7h7l
ixi: 
  blue: ro3qcd6s
  green: w32r74vo
  red: zs2m6862
  yellow: oggkzvq7
jetsam: 
  blue: w3rl2k9n
  green: cwss4w3s
  red: ghddf93g
  yellow: kz43rnld
jubjub: 
  blue: 8mf5gzov
  green: m267j935
  red: szckt2tj
  yellow: 78hdsnmw
kacheek: 
  blue: tvnq2l5s
  green: fkzfcb47
  red: 9hbtocjh
  yellow: 4gsrb59g
kau: 
  blue: ktlxmrtr
  green: x9ww69qo
  red: mrdtwkto
  yellow: 78w49w7x
kiko: 
  blue: 2qlfqqnd
  green: 42j5q3zx
  red: mcodrwlt
  yellow: 86b5xdn6
koi: 
  blue: tjvv5cq8
  green: ncfn87wk
  red: f3wvzz6r
  yellow: 4f6cvzgh
korbat: 
  blue: 4qxwv7w7
  green: d2ow9co8
  red: omx9c876
  yellow: nsxodd8z
kougra: 
  blue: rfsbh59t
  green: otvq569n
  red: x8hsckbh
  yellow: x7bbg59h
krawk: 
  blue: hxgsm5d4
  green: 7ngw8z4f
  red: kzwxb3dn
  yellow: m2gq59r5
kyrii: 
  blue: ojmo7qgg
  green: t3b8s9nz
  red: 6fvg9ngs
  yellow: blxmjgbk
lenny: 
  blue: jfc75n44
  green: 242k4kdq
  red: kc4w238d
  yellow: 8r94jhfq
lupe: 
  blue: r552fqj8
  green: ohmx4lc9
  red: 6jwlghsg
  yellow: z42535zh
lutari: 
  blue: qgg6z8s7
  green: wtjv7hw4
  red: lgws33oo
  yellow: 8x37fgjf
meerca: 
  blue: wwwhjf88
  green: lg9bb6tf
  red: v7g8w8w6
  yellow: kk2nn2jr
moehog: 
  blue: moot839l
  green: jgkoro5z
  red: dk47mfk8
  yellow: g84ovct7
mynci: 
  blue: xwlo9657
  green: s33qzokw
  red: f828tkrc
  yellow: tdfhsndr
nimmo: 
  blue: bx7fho8x
  green: mb4mcwj5
  red: mok2fcl4
  yellow: 9559onds
ogrin: 
  blue: 26v2sx49
  green: lg5bzqkq
  red: 3xgoz429
  yellow: rjzmx24v
peophin: 
  blue: 996t7zfg
  green: c9qo7zzt
  red: kokc52kh
  yellow: 4khvfnwl
poogle: 
  blue: 5n2vx7v2
  green: fw6lvf3c
  red: xhcwbdd5
  yellow: xozlhd68
pteri: 
  blue: 82d369sm
  green: slqmqr78
  red: tjhwbro3
  yellow: 4gkkb57f
quiggle: 
  blue: 4zs6b32m
  green: vbrsgqrl
  red: xrmt72wr
  yellow: jdto7mj4
ruki: 
  blue: qsgbm5f6
  green: vgml65cz
  red: sm55zs3q
  yellow: n43szv42
scorchio: 
  blue: ohb3b486
  green: kmb82xw8
  red: hkjoncsx
  yellow: hgfofbl2
shoyru: 
  blue: dj7n2zk8
  green: 3qwwn4n2
  red: 3zb2s2zw
  yellow: mmvn4tkg
skeith: 
  blue: 7c847jkn
  green: qdgwwz6c
  red: fc4cxk3t
  yellow: 533nc7rj
techo: 
  blue: vl8qro4r
  green: 2zc3vd47
  red: zgl2gjjn
  yellow: 84gvowmj
tonu: 
  blue: jd433863
  green: 6mcv27mn
  red: oskw3hqd
  yellow: 5bhqs7sv
tuskaninny: 
  blue: jj6t6cqd
  green: stl4mm78
  red: 48z4o75j
  yellow: q39wn6vq
uni: 
  blue: 74xvb24d
  green: njzvoflw
  red: jzfbdomk
  yellow: 5qdfrtcq
usul: 
  blue: xff976n8
  green: 5245lzmh
  red: rox4mgh5
  yellow: vxn8b4vr
wocky: 
  blue: xonntr5f
  green: 4ssorlcs
  red: 743smd5v
  yellow: dnr2kj4b
xweetok: 
  blue: ddhdrt2o
  green: thzwbqsq
  red: tdkqr2b6
  yellow: o36btnbf
yurble: 
  blue: nhn5lxb4
  green: mjgbr7vb
  red: h95cs547
  yellow: vfqkbvv6
zafara: 
  blue: x8c57g2l
  green: tq56zj3x
  red: n32sgrvm
  yellow: onxr95x6
