- label: Music
  depth: 1
  type_id: 4
  type: AUDIO_MUSIC
- label: Sound Effects
  depth: 2
  type_id: 4
  type: AUDIO_SOUND_EFFECTS
- label: Background
  depth: 3
  type_id: 3
  type: BACKGROUND
- label: Biology Effects
  depth: 6
  type_id: 1
  type: BIO_EFFECTS
- label: Hind Biology
  depth: 7
  type_id: 1
  type: BIO_HIND
- label: Markings
  depth: 8
  type_id: 2
  type: TATTOO
- label: Hind Disease
  depth: 9
  type_id: 1
  type: BIO_DISEASE_HIND
- label: Hind Cover
  depth: 10
  type_id: 2
  type: COVER_HIND
- label: Hind Transient Biology
  depth: 11
  type_id: 1
  type: TRANSIENT_BIO_HIND
- label: Hind Drippings
  depth: 12
  type_id: 1
  type: BIO_DRIPPINGS_HIND
- label: Backpack
  depth: 13
  type_id: 2
  type: BACKPACK
- label: Wings Transient Biology
  depth: 14
  type_id: 1
  type: TRANSIENT_BIO_WINGS
- label: Wings
  depth: 15
  type_id: 2
  type: WINGS
- label: Hair Back
  depth: 17
  type_id: 1
  type: TRANSIENT_BIO_HAIR_BACK
- label: Body
  depth: 18
  type_id: 1
  type: BIO_BODY
- label: Markings
  depth: 19
  type_id: 2
  type: TATTOO
- label: Body Disease
  depth: 20
  type_id: 1
  type: BIO_DISEASE_BODY
- label: Feet Transient Biology
  depth: 21
  type_id: 1
  type: TRANSIENT_BIO_FEET
- label: Shoes
  depth: 22
  type_id: 2
  type: SHOES
- label: Lower-body Transient Biology
  depth: 23
  type_id: 1
  type: TRANSIENT_BIO_BODY_LOWER
- label: Trousers
  depth: 24
  type_id: 2
  type: PANTS
- label: Upper-body Transient Biology
  depth: 25
  type_id: 1
  type: TRANSIENT_BIO_BODY_UPPER
- label: Shirt/Dress
  depth: 26
  type_id: 2
  type: SHIRT_DRESS
- label: Necklace
  depth: 28
  type_id: 2
  type: NECKLACE
- label: Gloves
  depth: 29
  type_id: 2
  type: COVER_HAND
- label: Jacket
  depth: 30
  type_id: 2
  type: JACKET
- label: Collar
  depth: 31
  type_id: 2
  type: COLLAR
- label: Body Drippings
  depth: 32
  type_id: 1
  type: BIO_DRIPPINGS_BODY
- label: Ruff
  depth: 33
  type_id: 1
  type: BIO_RUFF
- label: Head
  depth: 34
  type_id: 1
  type: BIO_HEAD
- label: Markings
  depth: 35
  type_id: 2
  type: TATTOO
- label: Head Disease
  depth: 36
  type_id: 1
  type: BIO_DISEASE_HEAD
- label: Eyes
  depth: 37
  type_id: 1
  type: BIO_EYES
- label: Mouth
  depth: 38
  type_id: 1
  type: BIO_MOUTH
- label: Glasses
  depth: 41
  type_id: 2
  type: GLASSES
- label: Earrings
  depth: 39
  type_id: 2
  type: EARRING
- label: Hair Front
  depth: 40
  type_id: 1
  type: TRANSIENT_BIO_HAIR_FRONT
- label: Head Transient Biology
  depth: 42
  type_id: 1
  type: TRANSIENT_BIO_HEAD
- label: Head Drippings
  depth: 43
  type_id: 1
  type: BIO_DRIPPINGS_HEAD
- label: Hat
  depth: 44
  type_id: 2
  type: HAT
- label: Earrings
  depth: 45
  type_id: 2
  type: EARRING
- label: Right-hand Item
  depth: 46
  type_id: 2
  type: ITEM_RIGHT_HAND
- label: Left-hand Item
  depth: 47
  type_id: 2
  type: ITEM_LEFT_HAND
- label: Higher Foreground Item
  depth: 49
  type_id: 3
  type: ITEM_FOREGROUND_HIGHER
- label: Lower Foreground Item
  depth: 50
  type_id: 3
  type: ITEM_FOREGROUND_LOWER
- label: Static
  depth: 48
  type_id: 3
  type: STATIC
- label: Thought Bubble
  depth: 51
  type_id: 3
  type: THOUGHT_BUBBLE
- label: Background Item
  depth: 4
  type_id: 3
  type: ITEM_BACKGROUND
- label: Right-hand Item
  depth: 5
  type_id: 2
  type: ITEM_RIGHT_HAND
- label: Hat
  depth: 16
  type_id: 2
  type: HAT
- label: Belt
  depth: 27
  type_id: 2
  type: BELT
- label: Foreground
  depth: 52
  type_id: 3
  type: TOP_FOREGROUND
